---
  pre_tasks:
    - name: upgrade all Redhat family packages
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: upgrade all Debian family packages
      apt:
        only_upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

  tasks:
    - name: Install Apache and Httpd
      tags: always
      package:
        name: "{{apache_package}}"
        state: present

    - name: Start and enable httpd (red-hat, amazon and centos).
      tags: apache,red-hat,httpd, fedora, amazon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start and Enable Apache2 (ubuntu)
      tags: apache,ubuntu,apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
...