# ansible n1 -m file -a "path=/home/ec2-user/new-dir state=directory"
---
- name: Update n1 servers
  hosts: n1
#  become: true

  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/new-dir
        state: directory

    - name: create directory
      file:
        path: /home/ec2-user/new-dir1
        state: directory

- name: Update n2 servers
  hosts: n2
  #  become: true

  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/new-dir1
        state: directory

    - name: create directory
      file:
        path: /home/ec2-user/new-dir2
        state: directory

- name: Update g1 servers
  hosts: g1
  #  become: true

  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/new-group1
        state: directory

    - name: create directory
      file:
        path: /home/ec2-user/new-group2
        state: directory
  