# ansible n1 -m file -a "path=/home/ec2-user/new-dir state=directory"
---
- name: Deploy Web App
  hosts: n2
  become: yes

  tasks:
    - name: Install Git
      yum:
        name: git
        state: present

    - name: Host code
      git:
        repo: https://github.com/ravi2krishna/ecomm.git
        dest: /var/www/html
        single_branch: yes
        version: master

...