# ansible n1 -m file -a "path=/home/ec2-user/new-dir state=directory"
---
- name: under maintenance
  hosts: n2
  become: yes

  tasks:
    - name: Update maintenance
      copy:
        src: maintenance.html
        dest: /var/www/html/index.html

...