# ansible n1 -m file -a "path=/home/ec2-user/new-dir state=directory"
---
- name: Install Apache2 server
  hosts: g1
  become: yes

  tasks:
    - name: Install Apache for ubuntu and red-hat
      tags: always
      package:
        name: "{{apache_package}}"

    - name: Start and enable httpd (red-hat, amazon and centos).
      tags: apache,red-hat,httpd, fedora, amazon
      service:
        name: httpd
        state: started
        enabled: yes
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution == "Amazon"
        - ansible_distribution == "Fedora"

    - name: Start and Enable Apache2 (ubuntu)
      tags: apache,ubuntu,apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution == "Debian"
...