# ansible n1 -m file -a "path=/home/ec2-user/new-dir state=directory"
---
- name: Dynamic page
  hosts: g1
  become: yes
  vars:
    myUsername: Toche

  tasks:
    - name: Update Dynamic page
      template:
        src: ~/ansible-work-5/dynamic.j2
        dest: /var/www/html/dynamic.html

