# ansible n1 -m file -a "path=/home/ec2-user/new-dir state=directory"
---
- name: Install HTTP server
  hosts: n2
  become: yes

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start Httpd
      service:
        name: httpd
        state: started

    - name: Enable Httpd
      service:
        name: httpd
        enabled: yes

...